cloud:
  aws:
    s3:
      bucket: mbti-talk-backend-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB