server:
  port: 3001

spring:
  profiles:
    include:
      - aws
      - aws-credential
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://mbti-talk-backend-db.c3qthxrb2jck.ap-northeast-2.rds.amazonaws.com/mbti-talk-backend-db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
    username: "admin"
    password: "rkdtlsgus1!"

cred:
  kakao:
    grant-type: authorization_code
    client-id: 51ebe5eee7b316d51aaf6b3aa6a87496
#    redirect-uri: http://localhost:3000/callback
    redirect-uri: https://mbti-talk-front-bucket.s3-website.ap-northeast-2.amazonaws.com/callback